name: root
channels:
- conda-forge
- defaults
dependencies:
- flask
- gunicorn
- pandas
- python
- rdkit
- scikit-learn=0.24.2
- nomkl
- numpy
- wtforms
- joblib
- pytest
- tensorflow>=2.6
- pytest
- pip
- pip:
  - alfabet==0.2.2
